server:
  port: 9896

spring:
  datasource:
    url: jdbc:mysql://192.168.121.254:3306/dpcpdp?characterEncoding=UTF-8&useSSL=false
    username: pgxcloud
    password: Pgxcloud2017Dev
    driver-class-name: com.mysql.cj.jdbc.Driver